# Generated by Django 3.2.9 on 2021-12-06 10:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20211205_1403'),
        ('trading', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('A', 'Accepted'), ('P', 'Pending'), ('R', 'Refused')], default='P', max_length=30)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.profile')),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trading.card')),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trading.transaction')),
            ],
        ),
    ]
