# Generated by Django 3.2.9 on 2021-12-05 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='thread',
            options={'ordering': ['-date']},
        ),
    ]
