# Generated by Django 3.2.9 on 2021-12-22 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_profile_image'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='typeprofile',
            constraint=models.UniqueConstraint(fields=('name',), name='unique name'),
        ),
        migrations.AlterModelTable(
            name='typeprofile',
            table='TypeProfile',
        ),
    ]
